/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InnovateRouteImport } from './routes/innovate'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as InnovateProjectSlugRouteImport } from './routes/innovate.$projectSlug'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CommunityDiscussionIdRouteImport } from './routes/community.$discussionId'
import { Route as ChallengesSlugRouteImport } from './routes/challenges.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedTalentRouteImport } from './routes/_authenticated/talent'
import { Route as AuthenticatedRequestAccessRouteImport } from './routes/_authenticated/request-access'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCvRouteImport } from './routes/_authenticated/cv'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAdvisorRouteImport } from './routes/_authenticated/advisor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedQuizzesQuizIdRouteImport } from './routes/_authenticated/quizzes.$quizId'
import { Route as AuthenticatedLessonsLessonIdRouteImport } from './routes/_authenticated/lessons.$lessonId'
import { Route as AuthenticatedInviteTokenRouteImport } from './routes/_authenticated/invite.$token'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminOpportunitiesRouteImport } from './routes/_authenticated/admin.opportunities'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovateRoute = InnovateRouteImport.update({
  id: '/innovate',
  path: '/innovate',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovateProjectSlugRoute = InnovateProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => InnovateRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityDiscussionIdRoute = CommunityDiscussionIdRouteImport.update({
  id: '/$discussionId',
  path: '/$discussionId',
  getParentRoute: () => CommunityRoute,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChallengesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalentRoute = AuthenticatedTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestAccessRoute =
  AuthenticatedRequestAccessRouteImport.update({
    id: '/request-access',
    path: '/request-access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvRoute = AuthenticatedCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvisorRoute = AuthenticatedAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedQuizzesQuizIdRoute =
  AuthenticatedQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsLessonIdRoute =
  AuthenticatedLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInviteTokenRoute =
  AuthenticatedInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesRoute =
  AuthenticatedAdminOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/innovate': typeof InnovateRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/cv': typeof AuthenticatedCvRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/request-access': typeof AuthenticatedRequestAccessRoute
  '/talent': typeof AuthenticatedTalentRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/community/$discussionId': typeof CommunityDiscussionIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/innovate/$projectSlug': typeof InnovateProjectSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/innovate': typeof InnovateRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/cv': typeof AuthenticatedCvRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/request-access': typeof AuthenticatedRequestAccessRoute
  '/talent': typeof AuthenticatedTalentRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/community/$discussionId': typeof CommunityDiscussionIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/innovate/$projectSlug': typeof InnovateProjectSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/innovate': typeof InnovateRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/advisor': typeof AuthenticatedAdvisorRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/cv': typeof AuthenticatedCvRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/request-access': typeof AuthenticatedRequestAccessRoute
  '/_authenticated/talent': typeof AuthenticatedTalentRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/community/$discussionId': typeof CommunityDiscussionIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/innovate/$projectSlug': typeof InnovateProjectSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/_authenticated/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/_authenticated/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/careers'
    | '/challenges'
    | '/community'
    | '/innovate'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/advisor'
    | '/applications'
    | '/certificates'
    | '/cv'
    | '/dashboard'
    | '/mentor'
    | '/portfolio'
    | '/request-access'
    | '/talent'
    | '/welcome'
    | '/api/chat'
    | '/blog/$slug'
    | '/challenges/$slug'
    | '/community/$discussionId'
    | '/courses/$courseId'
    | '/innovate/$projectSlug'
    | '/u/$userId'
    | '/blog/'
    | '/courses/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/invites'
    | '/admin/opportunities'
    | '/admin/requests'
    | '/admin/users'
    | '/invite/$token'
    | '/lessons/$lessonId'
    | '/quizzes/$quizId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/careers'
    | '/challenges'
    | '/community'
    | '/innovate'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/advisor'
    | '/applications'
    | '/certificates'
    | '/cv'
    | '/dashboard'
    | '/mentor'
    | '/portfolio'
    | '/request-access'
    | '/talent'
    | '/welcome'
    | '/api/chat'
    | '/blog/$slug'
    | '/challenges/$slug'
    | '/community/$discussionId'
    | '/courses/$courseId'
    | '/innovate/$projectSlug'
    | '/u/$userId'
    | '/blog'
    | '/courses'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/invites'
    | '/admin/opportunities'
    | '/admin/requests'
    | '/admin/users'
    | '/invite/$token'
    | '/lessons/$lessonId'
    | '/quizzes/$quizId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/careers'
    | '/challenges'
    | '/community'
    | '/innovate'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/advisor'
    | '/_authenticated/applications'
    | '/_authenticated/certificates'
    | '/_authenticated/cv'
    | '/_authenticated/dashboard'
    | '/_authenticated/mentor'
    | '/_authenticated/portfolio'
    | '/_authenticated/request-access'
    | '/_authenticated/talent'
    | '/_authenticated/welcome'
    | '/api/chat'
    | '/blog/$slug'
    | '/challenges/$slug'
    | '/community/$discussionId'
    | '/courses/$courseId'
    | '/innovate/$projectSlug'
    | '/u/$userId'
    | '/blog/'
    | '/courses/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/opportunities'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/users'
    | '/_authenticated/invite/$token'
    | '/_authenticated/lessons/$lessonId'
    | '/_authenticated/quizzes/$quizId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  InnovateRoute: typeof InnovateRouteWithChildren
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  UUserIdRoute: typeof UUserIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovate': {
      id: '/innovate'
      path: '/innovate'
      fullPath: '/innovate'
      preLoaderRoute: typeof InnovateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovate/$projectSlug': {
      id: '/innovate/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/innovate/$projectSlug'
      preLoaderRoute: typeof InnovateProjectSlugRouteImport
      parentRoute: typeof InnovateRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$discussionId': {
      id: '/community/$discussionId'
      path: '/$discussionId'
      fullPath: '/community/$discussionId'
      preLoaderRoute: typeof CommunityDiscussionIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talent': {
      id: '/_authenticated/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof AuthenticatedTalentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/request-access': {
      id: '/_authenticated/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof AuthenticatedRequestAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv': {
      id: '/_authenticated/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AuthenticatedCvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advisor': {
      id: '/_authenticated/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AuthenticatedAdvisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/quizzes/$quizId': {
      id: '/_authenticated/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$lessonId': {
      id: '/_authenticated/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite/$token': {
      id: '/_authenticated/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthenticatedInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/opportunities': {
      id: '/_authenticated/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminOpportunitiesRoute: typeof AuthenticatedAdminOpportunitiesRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminOpportunitiesRoute: AuthenticatedAdminOpportunitiesRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAdvisorRoute: typeof AuthenticatedAdvisorRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedCvRoute: typeof AuthenticatedCvRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedRequestAccessRoute: typeof AuthenticatedRequestAccessRoute
  AuthenticatedTalentRoute: typeof AuthenticatedTalentRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedInviteTokenRoute: typeof AuthenticatedInviteTokenRoute
  AuthenticatedLessonsLessonIdRoute: typeof AuthenticatedLessonsLessonIdRoute
  AuthenticatedQuizzesQuizIdRoute: typeof AuthenticatedQuizzesQuizIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAdvisorRoute: AuthenticatedAdvisorRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedCvRoute: AuthenticatedCvRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedRequestAccessRoute: AuthenticatedRequestAccessRoute,
  AuthenticatedTalentRoute: AuthenticatedTalentRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedInviteTokenRoute: AuthenticatedInviteTokenRoute,
  AuthenticatedLessonsLessonIdRoute: AuthenticatedLessonsLessonIdRoute,
  AuthenticatedQuizzesQuizIdRoute: AuthenticatedQuizzesQuizIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChallengesRouteChildren {
  ChallengesSlugRoute: typeof ChallengesSlugRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesSlugRoute: ChallengesSlugRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

interface CommunityRouteChildren {
  CommunityDiscussionIdRoute: typeof CommunityDiscussionIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityDiscussionIdRoute: CommunityDiscussionIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface InnovateRouteChildren {
  InnovateProjectSlugRoute: typeof InnovateProjectSlugRoute
}

const InnovateRouteChildren: InnovateRouteChildren = {
  InnovateProjectSlugRoute: InnovateProjectSlugRoute,
}

const InnovateRouteWithChildren = InnovateRoute._addFileChildren(
  InnovateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  InnovateRoute: InnovateRouteWithChildren,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  UUserIdRoute: UUserIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
